### ISSUE TITLE
where is 'client.properties'?

### ISSUE THREAD

**Issue by jhunahn** [blackducksoftware/protex-jenkins#5]
Hi, I am jihun.
I am trying to apply this plugin to my jenkins server.

Unfortunately, I have some problems.
When using 'BDSTOOL', I could modify the 'client.property' file to modify the proxy server and port.
But, when I apply this plugin, I can't knows how to set this up.

My protex server should not be configured for 'proxy'(also, set to 'no_proxy' in my PC).

Would you mind if you help me to set this up?

Thank.

**Comment by utsavsanghani** [comment]
Hi Jihun,

We officially stopped support for this plugin in 2016. Your best option at this time is to use the plugin along with documentation that comes with Protex to set it up yourself.
